name: kids_bids
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.9
  fluttertoast: ^8.1.3
  shimmer: ^2.0.0
  auto_size_text: ^3.0.0
  get: ^4.6.5
  lottie: ^2.2.0



flutter:
  uses-material-design: true
  assets:
      - assets/icon/
      - assets/logo/
      - assets/image/
      - assets/items/
      - assets/fruits/
      - assets/shape/
      - assets/lotties/
 

  